{% set name = "handy-archives" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/handy-archives-{{ version }}.tar.gz
  sha256: 320280f17dd90501e8297f1b5dfc61447e92efa47590b23d71ba67c62db2db42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - domdf-python-tools >=3.1.0
    - python >=3.6

test:
  imports:
    - handy_archives
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/handy-archives/
  summary: Some handy archive helpers for Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://handy-archives.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
