{% set name = "handy-archives" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fba21101fd9e29d5e3b72823261aaae06b9350686f0d2067786d64dce73eb3f6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - handy_archives
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/domdfcoding/handy-archives/
  summary: Some handy archive helpers for Python.
  license: MIT
  license_file: LICENSE
  doc_url: https://handy-archives.readthedocs.io/en/latest

extra:
  recipe-maintainers:
    - domdfcoding
